name: Update playlist

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Remove dead sources
        run: python3 tools/remove_dead_sources.py

      - name: Update playlist
        run: python3 ./make_playlist.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update playlist and disable dead sources"
